print("today's practice")
print("Hello world")
print("data science class 11")
print("data science")
print("it is not staged")
print('staging test')
print("an extra code")
print("debugging the added code")
print(2+2)
